log-level = "WARNING"

[kafka]
servers = [ "server:9092" ]
ssl_ca_cert = "/etc/wamukap/ca-cert.pem"
ssl_cert = "/etc/wamukap/cert.pem"
ssl_cert_key = "/etc/wamukap/cert-key.key"
topic = "wamukap"
consumer_group_id = "wamukap"

[watcher]
interval = 10

[[watcher.sites]]
url = "https://aiven.com/"
regexp = "html"

[[watcher.sites]]
url = "http://h4kamp.net/"
interval = 1

[[watcher.sites]]
url = "http://domain-doesnt-exist-abc.com/"

[[watcher.sites]]
url = "http://google.com/"
interval = 2

[database]
host = "hostname"
port = 18935
database = "wamukap"
user = "dbuser"
password = "secret"
sslmode = "require"
sslrootcert = "/etc/wamukap/ca-cert.pem"
